# Generated by Django 4.1.5 on 2023-01-24 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VrstaSmjera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smjera', models.CharField(max_length=200)),
                ('kvota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prijavnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_rodjenja', models.DateTimeField()),
                ('mjesto_rodjenja', models.CharField(max_length=200)),
                ('zavrsena_skola', models.CharField(max_length=200)),
                ('molba_za_upis_na_smjer', models.TextField()),
                ('dokument_o_zavrsenoj_skoli', models.FileField(upload_to='dokumetiskola')),
                ('prosjek_ocjena', models.FloatField()),
                ('ocjena_na_maturi', models.FloatField()),
                ('status', models.CharField(choices=[('0', 'U obradi'), ('1', 'Odobreno'), ('2', 'Odbijeno')], default='0', max_length=1)),
                ('datum_kriranja', models.DateTimeField(verbose_name='date published')),
                ('odabir_smjera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upisi.vrstasmjera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_predmeta', models.CharField(max_length=200)),
                ('ECTS', models.IntegerField()),
                ('opis_predmeta', models.TextField()),
                ('smjer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upisi.vrstasmjera')),
            ],
        ),
        migrations.CreateModel(
            name='LOG_upisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_odobrenja', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('1', 'Odobreno'), ('2', 'Odbijeno')], max_length=1)),
                ('vrijeme_odobrenja', models.DateTimeField(verbose_name='date published')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prijavnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upisi.prijavnica')),
            ],
        ),
    ]
